In [1]:
import numpy as np
import pandas as pd
import sys
from IPython.display import display

In [2]:
amn_data = pd.read_csv("../data_files/clean-combined-amns.csv")
nbr_data = pd.read_csv('../data_files/clean-nbr-coords.csv')
amn_data = pd.read_csv('./../data_files/clean-combined-amns.csv') 
amn_in_range_data = pd.read_csv('./../data_files/nbr-amenity-is-near.csv') 

airbnb_data = pd.read_csv('./../data_files/clean-airbnb-listings.csv')

/home/gloria/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3444: DtypeWarning: Columns (28,31,37,44,46,49,61,67,68,69,73,74,89,90,91,93,100,105,112,130,131,140,148,151,157,158,160,163,164,165,166,167,169,170,172,174,180,184,187,189,191,192,199,202,203,206,208,218,219,220,229,233,234,235,236,241,243,244,245,259,261,262,264,265,266,269,270,271,272,275,281,284,285,286,293,300,302,303,304,306,315,317,319,321,322,323,324,325,327,333,334,335,350,355,359,362,364,365,369,373,374,375,377,379,383,384,387,388,394,395,396,397,398,411,412,418) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [3]:
def haversine(coords1, coords2):
    # radius of earth & haversine formula: 
    # https://en.wikipedia.org/wiki/Haversine_formula

    r = 6371000 # in meters

    lat_diff = np.radians(coords1['lat'] - coords2['lat'])
    lon_diff = np.radians(coords1['lon'] - coords2['lon'])
    lat1 = np.radians(coords2['lat'])
    lat2 = np.radians(coords1['lat'])

    h_sin2_lat = np.square(np.sin(lat_diff/2))
    h_sin2_lon = np.square(np.sin(lon_diff/2))
    h_sqrt = np.sqrt(h_sin2_lat + (np.cos(lat1) * np.cos(lat2) * h_sin2_lon))
    h_dist = 2 * r * np.arcsin(h_sqrt)

    return h_dist

In [4]:
numOfAmenities = amn_data.shape[0]
numOfNeighbourhoods = nbr_data.shape[0]
numOfListings = airbnb_data.shape[0]


# display(nbr_data)

# TEST DATA STARTS HERE

In [5]:
chosen_nbr = "Sunset"
chosen_amns = ['sustenance', 'transportation']

In [6]:
curr_nbr_data = nbr_data[nbr_data['neighbourhood'] == chosen_nbr]
# top_airbnb_data = pd.DataFrame()
# top_airbnb_data = get_shelter_suggestions(chosen_nbr, chosen_amns)

In [7]:
# def get_shelter_suggestions

# filter listings by neighbourhood
airbnb_nbr = airbnb_data[airbnb_data['neighbourhood_cleansed'] == chosen_nbr]

# filter listings by required (prioritized) amenities 
# airbnb_nbr_amn, amn_inRange = get_shelters_by_amenities(airbnb_nbr, amenity_types, range)

In [12]:
# def get_desired_amenities
maxRange = 500
# numOfListings = airbnb_nbr.shape[0]
chosen_amn_data = amn_data[amn_data['amenity'].isin(chosen_amns)]
chosen_amn_data = chosen_amn_data.rename(columns={'Unnamed: 0': 'id'})




nbr_amn_data = amn_in_range_data[amn_in_range_data['neighbourhood'] == chosen_nbr]

# amn_ids = chosen_amn_data.columns[0]

# chosen_amn_data = chosen_amn_data.filter(nbr_amn_data[chosen_amn_data[amn_ids].astype(str)].notna(), axis=0)

# display(chosen_amn_data[nbr_amn_data[chosen_amn_data['Unnamed: 0']] != 'NaN'])
nbr_amn_ids = nbr_amn_data.columns[(nbr_amn_data.notna()).iloc[0]].tolist()

nbr_amn_ids = nbr_amn_ids[2:]

nbr_amn_ids = [int(i) for i in nbr_amn_ids]

# nbr_amn_data = nbr_amn_data[nbr_amn_data[0].isinnbr_amn_ids]]


# nbr_amn_data = nbr_amn_data.iloc[0]



# display(nbr_amn_ids)
# display(chosen_amn_data)

chosen_amn_data = chosen_amn_data[chosen_amn_data['id'].isin(nbr_amn_ids)]
airbnb_nbr = airbnb_nbr.rename(columns={'latitude': 'lat', 'longitude': 'lon'})


display(chosen_amn_data)
display(airbnb_nbr)

,id,lat,lon,amenity,name,brand:wikidata,official_name,addr:housenumber,brand:wikipedia,opening_hours,...,socket:tesla_supercharger:output,authentication:nfc,diet:organic,outdoor_seating:comfort,source:addr,authentication:none,voltage,townhall:type,recycling:cars,Name
540,540,49.218256,-123.077381,sustenance,McDonald's,Q38076,NaN,7295,en:McDonald's,24/7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1313,1313,49.218939,-123.091186,sustenance,Dosa Hut,NaN,NaN,7233,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1459,1459,49.210637,-123.092206,sustenance,Panos,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1969,1969,49.225258,-123.090384,sustenance,Sushi Moon,NaN,NaN,6520,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1970,1970,49.225152,-123.090470,sustenance,Starbucks,Q37158,Starbucks Coffee,6544,en:Starbucks,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1971,1971,49.224846,-123.090979,sustenance,Shoom Restaurant,NaN,NaN,6555,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1972,1972,49.224659,-123.090979,sustenance,Yu Xiang Yuan Restaurant,NaN,NaN,6591,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4368,4368,49.218345,-123.077379,sustenance,Subway,Q244457,NaN,7289,en:Subway (restaurant),NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4531,4531,49.210626,-123.092382,sustenance,Neptune Chinese Kitchen,NaN,NaN,620,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4605,4605,49.225109,-123.090970,sustenance,Breka Bakery & Café,NaN,NaN,6533,NaN,24/7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5433,5433,49.223970,-123.091035,sustenance,New Novelty Restaurant,NaN,NaN,NaN,NaN,Mo-Su 10:30-21:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5644,5644,49.218839,-123.101578,sustenance,Best Quality Sweets & Restaurant,NaN,NaN,7260,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5645,5645,49.219095,-123.102085,sustenance,Original Tandoori Kitchen,NaN,NaN,7215,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

,Unnamed: 0,name,neighbourhood_cleansed,lat,lon,listing_url,number_of_reviews_ltm,review_scores_rating
411,411,Stay here for your family ready-made Christmas!,Sunset,49.21700,-123.09479,https://www.airbnb.com/rooms/6977279,4,4.86
413,413,4BR Vancouver Special @ Langara,Sunset,49.22261,-123.10396,https://www.airbnb.com/rooms/7022315,0,4.76
424,424,Family Friendly Home Minutes from Downtown and...,Sunset,49.22013,-123.09624,https://www.airbnb.com/rooms/7146259,20,4.46
472,472,Gorgeous new townhouse with 2 King Size beds,Sunset,49.23191,-123.09369,https://www.airbnb.com/rooms/7986252,0,5.00
503,503,Vancouver Green Garden Oasis,Sunset,49.22846,-123.09686,https://www.airbnb.com/rooms/8672239,18,4.90
...,...,...,...,...,...,...,...,...
4077,4077,A Cute & Cozy 2 Beds Suite near QE Park,Sunset,49.22860,-123.10228,https://www.airbnb.com/rooms/51453218,17,5.00
4084,4084,Spacious 2 bdrm suite in a quiet residential a...,Sunset,49.22643,-123.09187,https://www.airbnb.com/rooms/51468414,3,5.00
4206,4206,Casa St.George,Sunset,49.23139,-123.09504,https://www.airbnb.com/rooms/52044026,1,5.00
4252,4252,3BR Cosy Laneway House / Up to 8 guests / AC,Sunset,49.23157,-123.07855,https://www.airbnb.com/rooms/52370725,2,3.50
4267,4267,2-bedroom Private Suite in Sunset Area,Sunset,49.21347,-123.10180,https://www.airbnb.com/rooms/52446690,2,3.00

In [27]:
# rank listings based on close they are to each of the desired amenities
# display(airbnb_nbr)

numOfListings = airbnb_nbr.shape[0]
numOfAmenities = chosen_amn_data.shape[0]

amn_scores = []
for i in range (numOfListings):
    airbnb_row = airbnb_nbr.iloc[i]
   
    airbnb_dists = chosen_amn_data.apply(haversine, coords2=airbnb_nbr.iloc[i], axis=1)

    airbnb_dists_sum = airbnb_dists.sum()

    amn_scores.append(airbnb_dists_sum)
    # airbnb_nbr.iloc[i]['amn_score'] = airbnb_dists_sum

airbnb_nbr['amn_score'] = amn_scores

# airbnb_dist_score = chosen_amn_data.apply(lambda x,y: haversine(x, coords2=airbnb_nbr.iloc[i, axis=1)

display(amn_scores)

display(airbnb_row)


display(airbnb_nbr)

[10966.774254511805,
 14943.958087967369,
 10135.767700451766,
 18035.232093308616,
 14599.224281910987,
 13526.329870011976,
 13836.60686083429,
 9809.135169082469,
 17957.612134735602,
 14259.377319778887,
 17659.08369313925,
 10094.01059381913,
 15930.408340363014,
 9925.791085988985,
 10195.232240045189,
 15168.528431436298,
 14144.047257901848,
 16715.61082619635,
 14696.847001677574,
 14592.100133452032,
 11824.196211323353,
 21687.215751536456,
 20448.687751539346,
 17146.303474622604,
 17971.3127389076,
 14431.453046133438,
 13512.015031333009,
 22608.988176886556,
 9269.59876689111,
 11763.365802521137,
 12007.90394445868,
 13705.91340627496,
 10291.375982965566,
 18668.28430871608,
 19476.212896022687,
 12578.342098287298,
 14104.736323920242,
 18203.140137959814,
 18330.813635489158,
 8533.773150878826,
 11998.282222049264,
 13061.133790902231,
 19586.835608083376,
 20033.96737720212,
 17139.413887205377,
 14522.833221595278,
 15843.950823001316,
 9182.9915744413,
 17248.10816594967,
 16264.616198285647,
 13217.003948334683,
 14149.089585914513,
 16972.115074612284,
 12099.450302546633,
 16180.710025831848,
 17066.655878235393,
 12924.303032362295,
 13719.743604316887,
 8678.93688644216,
 12372.145623302895,
 12631.58933224043,
 15711.21630543723,
 9170.514044522104,
 13329.15305803423,
 20182.62261528471,
 20614.64218874697,
 8587.473915873381,
 12899.694625463617,
 12116.500777771293,
 14557.618922406438,
 11153.389023293377,
 18987.45795384339,
 20405.02955413133,
 17622.979309251263,
 10504.907394393183,
 17612.46756698657,
 21073.168628098887,
 16399.292728492783]

Unnamed: 0                                                  4267
name                      2-bedroom Private Suite in Sunset Area
neighbourhood_cleansed                                    Sunset
lat                                                     49.21347
lon                                                    -123.1018
listing_url                https://www.airbnb.com/rooms/52446690
number_of_reviews_ltm                                          2
review_scores_rating                                         3.0
amn_score                                           16399.292728
Name: 4267, dtype: object

,Unnamed: 0,name,neighbourhood_cleansed,lat,lon,listing_url,number_of_reviews_ltm,review_scores_rating,amn_score
411,411,Stay here for your family ready-made Christmas!,Sunset,49.21700,-123.09479,https://www.airbnb.com/rooms/6977279,4,4.86,10966.774255
413,413,4BR Vancouver Special @ Langara,Sunset,49.22261,-123.10396,https://www.airbnb.com/rooms/7022315,0,4.76,14943.958088
424,424,Family Friendly Home Minutes from Downtown and...,Sunset,49.22013,-123.09624,https://www.airbnb.com/rooms/7146259,20,4.46,10135.767700
472,472,Gorgeous new townhouse with 2 King Size beds,Sunset,49.23191,-123.09369,https://www.airbnb.com/rooms/7986252,0,5.00,18035.232093
503,503,Vancouver Green Garden Oasis,Sunset,49.22846,-123.09686,https://www.airbnb.com/rooms/8672239,18,4.90,14599.224282
...,...,...,...,...,...,...,...,...,...
4077,4077,A Cute & Cozy 2 Beds Suite near QE Park,Sunset,49.22860,-123.10228,https://www.airbnb.com/rooms/51453218,17,5.00,17622.979309
4084,4084,Spacious 2 bdrm suite in a quiet residential a...,Sunset,49.22643,-123.09187,https://www.airbnb.com/rooms/51468414,3,5.00,10504.907394
4206,4206,Casa St.George,Sunset,49.23139,-123.09504,https://www.airbnb.com/rooms/52044026,1,5.00,17612.467567
4252,4252,3BR Cosy Laneway House / Up to 8 guests / AC,Sunset,49.23157,-123.07855,https://www.airbnb.com/rooms/52370725,2,3.50,21073.168628
4267,4267,2-bedroom Private Suite in Sunset Area,Sunset,49.21347,-123.10180,https://www.airbnb.com/rooms/52446690,2,3.00,16399.292728

In [40]:
# normalize amenitiy distances (scores)
new_min, new_max = 1, 5
old_min, old_max = airbnb_nbr['amn_score'].min(), airbnb_nbr['amn_score'].max()
airbnb_nbr['amn_score'] = (airbnb_nbr['amn_score'] - old_min) / (old_max - old_min) * (new_max - new_min) + new_min

display(airbnb_nbr['review_scores_rating'])

airbnb_nbr['combined_score'] = airbnb_nbr['review_scores_rating'] + airbnb_nbr['amn_score']

if airbnb_nbr.shape[0] > 5:
    airbnb_nbr = airbnb_nbr.nlargest(5, ['combined_score'])

display(airbnb_nbr)

1172    4.99
1711    4.50
1176    5.00
1901    4.95
2204    4.91
Name: review_scores_rating, dtype: float64

,Unnamed: 0,name,neighbourhood_cleansed,lat,lon,listing_url,number_of_reviews_ltm,review_scores_rating,amn_score,combined_score
1172,1172,"NEW Main St suite - Deluxe Hotel Style, Local ...",Sunset,49.23138,-123.10445,https://www.airbnb.com/rooms/21281197,33,4.99,3.823060,8.813060
1711,1711,Main Street bedroom,Sunset,49.23244,-123.10406,https://www.airbnb.com/rooms/27759917,0,4.50,5.000000,9.500000
1176,1176,The Sherbrooke Laneway,Sunset,49.23260,-123.08251,https://www.airbnb.com/rooms/21363777,4,5.00,2.241678,7.241678
1901,1901,Stylish 7 bed/6 bth city-center family home,Sunset,49.23157,-123.09974,https://www.airbnb.com/rooms/30373419,10,4.95,1.000000,5.950000
2204,2204,Private Comfortable Guest House,Sunset,49.22877,-123.10511,https://www.airbnb.com/rooms/34513875,5,4.91,1.141246,6.051246