In [16]:
import numpy as np
import pandas as pd
import sys
from IPython.display import display

In [17]:
amn_data = pd.read_csv("../data_files/clean-combined-amns.csv")
nbr_data = pd.read_csv('../data_files/clean-nbr-coords.csv')
amn_data = pd.read_csv('./../data_files/clean-combined-amns.csv') 
amn_in_range_data = pd.read_csv('./../data_files/nbr-amenity-is-near.csv') 

airbnb_data = pd.read_csv('./../data_files/clean-airbnb-listings.csv')

/home/gloria/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3444: DtypeWarning: Columns (28,31,37,44,46,49,61,67,68,69,73,74,89,90,91,93,100,105,112,130,131,140,148,151,157,158,160,163,164,165,166,167,169,170,172,174,180,184,187,189,191,192,199,202,203,206,208,218,219,220,229,233,234,235,236,241,243,244,245,259,261,262,264,265,266,269,270,271,272,275,281,284,285,286,293,300,302,303,304,306,315,317,319,321,322,323,324,325,327,333,334,335,350,355,359,362,364,365,369,373,374,375,377,379,383,384,387,388,394,395,396,397,398,411,412,418) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [18]:
def haversine(coords1, coords2):
    # radius of earth & haversine formula: 
    # https://en.wikipedia.org/wiki/Haversine_formula

    r = 6371000 # in meters

    lat_diff = np.radians(coords1['lat'] - coords2['lat'])
    lon_diff = np.radians(coords1['lon'] - coords2['lon'])
    lat1 = np.radians(coords2['lat'])
    lat2 = np.radians(coords1['lat'])

    h_sin2_lat = np.square(np.sin(lat_diff/2))
    h_sin2_lon = np.square(np.sin(lon_diff/2))
    h_sqrt = np.sqrt(h_sin2_lat + (np.cos(lat1) * np.cos(lat2) * h_sin2_lon))
    h_dist = 2 * r * np.arcsin(h_sqrt)

    return h_dist

In [19]:
numOfAmenities = amn_data.shape[0]
numOfNeighbourhoods = nbr_data.shape[0]
numOfListings = airbnb_data.shape[0]


# display(nbr_data)

# TEST DATA STARTS HERE

In [20]:
chosen_nbr = "Sunset"
chosen_amns = ['sustenance', 'transportation']

In [21]:
curr_nbr_data = nbr_data[nbr_data['neighbourhood'] == chosen_nbr]
# top_airbnb_data = pd.DataFrame()
# top_airbnb_data = get_shelter_suggestions(chosen_nbr, chosen_amns)

In [22]:
# def get_shelter_suggestions

# filter listings by neighbourhood
airbnb_nbr = airbnb_data[airbnb_data['neighbourhood_cleansed'] == chosen_nbr]

# filter listings by required (prioritized) amenities 
# airbnb_nbr_amn, amn_inRange = get_shelters_by_amenities(airbnb_nbr, amenity_types, range)

In [85]:
# def get_shelters_by_amenities
range = 500
# numOfListings = airbnb_nbr.shape[0]
chosen_amn_data = amn_data[amn_data['amenity'].isin(chosen_amns)]
chosen_amn_data = chosen_amn_data.rename(columns={'Unnamed: 0': 'id'})




nbr_amn_data = amn_in_range_data[amn_in_range_data['neighbourhood'] == chosen_nbr]

# amn_ids = chosen_amn_data.columns[0]

# chosen_amn_data = chosen_amn_data.filter(nbr_amn_data[chosen_amn_data[amn_ids].astype(str)].notna(), axis=0)

# display(chosen_amn_data[nbr_amn_data[chosen_amn_data['Unnamed: 0']] != 'NaN'])
nbr_amn_ids = nbr_amn_data.columns[(nbr_amn_data.notna()).iloc[0]].tolist()

nbr_amn_ids = nbr_amn_ids[2:]

nbr_amn_ids = [int(i) for i in nbr_amn_ids]

# nbr_amn_data = nbr_amn_data[nbr_amn_data[0].isinnbr_amn_ids]]


# nbr_amn_data = nbr_amn_data.iloc[0]



# display(nbr_amn_ids)
# display(chosen_amn_data)

chosen_amn_data = chosen_amn_data[chosen_amn_data['id'].isin(nbr_amn_ids)]

display(chosen_amn_data)

,id,lat,lon,amenity,name,brand:wikidata,official_name,addr:housenumber,brand:wikipedia,opening_hours,...,socket:tesla_supercharger:output,authentication:nfc,diet:organic,outdoor_seating:comfort,source:addr,authentication:none,voltage,townhall:type,recycling:cars,Name
540,540,49.218256,-123.077381,sustenance,McDonald's,Q38076,NaN,7295,en:McDonald's,24/7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1313,1313,49.218939,-123.091186,sustenance,Dosa Hut,NaN,NaN,7233,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1459,1459,49.210637,-123.092206,sustenance,Panos,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1969,1969,49.225258,-123.090384,sustenance,Sushi Moon,NaN,NaN,6520,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1970,1970,49.225152,-123.090470,sustenance,Starbucks,Q37158,Starbucks Coffee,6544,en:Starbucks,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1971,1971,49.224846,-123.090979,sustenance,Shoom Restaurant,NaN,NaN,6555,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1972,1972,49.224659,-123.090979,sustenance,Yu Xiang Yuan Restaurant,NaN,NaN,6591,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4368,4368,49.218345,-123.077379,sustenance,Subway,Q244457,NaN,7289,en:Subway (restaurant),NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4531,4531,49.210626,-123.092382,sustenance,Neptune Chinese Kitchen,NaN,NaN,620,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4605,4605,49.225109,-123.090970,sustenance,Breka Bakery & Café,NaN,NaN,6533,NaN,24/7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5433,5433,49.223970,-123.091035,sustenance,New Novelty Restaurant,NaN,NaN,NaN,NaN,Mo-Su 10:30-21:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5644,5644,49.218839,-123.101578,sustenance,Best Quality Sweets & Restaurant,NaN,NaN,7260,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5645,5645,49.219095,-123.102085,sustenance,Original Tandoori Kitchen,NaN,NaN,7215,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
for i in range (numOfAmenities):
    dists = nbr_data.apply(haversine, coords2=amn_data.iloc[i] , axis=1)
    # only include amenities within 1km
    dists_inRange = dists.where(dists < 1000)
    dist_list = dists_inRange
    nbr_nearby_amenities[i] = dists_inRange

/tmp/ipykernel_115714/2202602082.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
  nbr_nearby_amenities[i] = dists_inRange

In [ ]:
# display(dists_inRange)
display(nbr_nearby_amenities)

,neighbourhood,0,1,2,3,4,5,6,7,8,...,7783,7784,7785,7786,7787,7788,7789,7790,7791,7792
0,Arbutus Ridge,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,945.498742,NaN,NaN,NaN,NaN,NaN,NaN
1,Downtown,NaN,NaN,NaN,751.282914,790.62661,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Downtown Eastside,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Dunbar-Southlands,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Fairview,566.484839,555.980911,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,621.146772,NaN,NaN
5,Grandview-Woodland,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Hastings-Sunrise,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Kensington-Cedar Cottage,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Kerrisdale,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Killarney,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Kitsilano,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,630.409197,NaN,NaN,NaN,NaN,NaN,NaN
11,Marpole,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,888.770796,NaN,NaN,NaN,NaN
12,Mount Pleasant,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,859.482299
13,Oakridge,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,785.945634,NaN,NaN,NaN,NaN,NaN
14,Renfrew-Collingwood,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,Riley Park,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Shaughnessy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,South Cambie,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Strathcona,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,Sunset,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,Victoria-Fraserview,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,664.269825,95.432419,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,West End,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,734.764681,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,West Point Grey,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,789.097269,NaN,NaN,NaN

In [ ]:
nbr_nearby_amenities.to_csv('../data_files/nbr-amenity-is-near.csv')